# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05bb5b872f9460feca2511c61be343281fc5387962b87b7dec68f40dd5c6615e9344531e4dd40936504485da87aaacd4a1ba60a3a13e3cf1470aec3ec698bc39

test:
  secret_key_base: 301dc1b0b0cb21807bafc23d325b1bc551fe4a983548d507b1e7b9e4d710ac991b2f58eaeac91ff9cd08263e680deb1f996c9f475c6afb75450f0cf2ae37d920

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
